// Maps each TESTCASE ID → {specFile, testTitle, stepName}
// Used by generateTestCases.js (to fill mapping columns) and update-results.js (to find result in Playwright JSON)
// stepName: '' means the test has no test.step() — match at test level
// '' for any field means: not automated / manual TC

export const TC_MAPPING = {
    // ── LOGIN ─────────────────────────────────────────────────────────────
    TC_LOGIN_001: { specFile: 'web/tests/login.spec.js', testTitle: 'Login as OBC admin', stepName: '' },
    TC_LOGIN_002: { specFile: 'web/tests/login.spec.js', testTitle: 'Login as OBC admin', stepName: '' },
    TC_LOGIN_003: { specFile: 'web/tests/login.spec.js', testTitle: 'Login as OBC admin', stepName: '' },
    TC_LOGIN_004: { specFile: 'web/tests/login.spec.js', testTitle: 'Login as OBC admin', stepName: '' },
    TC_LOGIN_005: { specFile: 'web/tests/login.spec.js', testTitle: 'Login as OBC admin', stepName: '' },
    TC_LOGIN_006: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Login as Seg' },
    TC_LOGIN_007: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Login as Cash' },
    TC_LOGIN_008: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Login as Seg CA' },
    TC_LOGIN_009: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Login with mobile + PIN' },
    TC_LOGIN_010: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Login with mobile + PIN' },
    TC_LOGIN_011: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Login with mobile + PIN' },
    TC_LOGIN_012: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Login with mobile + PIN' },
    TC_LOGIN_013: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Login with mobile + PIN' },
    TC_LOGIN_014: { specFile: 'web/tests/login.spec.js', testTitle: 'Logout', stepName: '' },
    TC_LOGIN_015: { specFile: 'web/tests/login.spec.js', testTitle: 'Logout', stepName: '' },
    TC_LOGIN_016: { specFile: 'web/tests/login.spec.js', testTitle: 'Logout', stepName: '' },
    TC_LOGIN_017: { specFile: 'web/tests/login.spec.js', testTitle: 'Logout', stepName: '' },

    // ── SO UPLOAD ─────────────────────────────────────────────────────────
    TC_SOU_001: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Open SO upload form' },
    TC_SOU_002: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Open SO upload form' },
    TC_SOU_003: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Open SO upload form' },
    TC_SOU_004: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Open SO upload form' },
    TC_SOU_005: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_006: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_007: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_008: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_009: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_010: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_SOU_011: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Upload SO Report, Invoice Report, Sales Register' },
    TC_SOU_012: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Upload SO Report, Invoice Report, Sales Register' },
    TC_SOU_013: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Upload SO Report, Invoice Report, Sales Register' },
    TC_SOU_014: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Submit and observe response' },
    TC_SOU_015: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Submit and observe response' },
    TC_SOU_016: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_017: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_018: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_019: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_020: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_021: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_022: { specFile: '', testTitle: '', stepName: '' }, // negative - manual
    TC_SOU_023: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_024: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_025: { specFile: '', testTitle: '', stepName: '' }, // negative - manual
    TC_SOU_026: { specFile: 'web/tests/soUpload.spec.js', testTitle: 'Upload SO/Invoice/SR files for CMBT Britannia', stepName: 'Wait for fully processed and capture invoices' },
    TC_SOU_027: { specFile: '', testTitle: '', stepName: '' }, // negative - manual

    // ── DELIVERY ALLOCATION ───────────────────────────────────────────────
    TC_DA_001: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Open Delivery Allocation form' },
    TC_DA_002: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Open Delivery Allocation form' },
    TC_DA_003: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Open Delivery Allocation form' },
    TC_DA_004: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Select invoices and click Allocate Vehicle' },
    TC_DA_005: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Select invoices and click Allocate Vehicle' },
    TC_DA_006: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Select invoices and click Allocate Vehicle' },
    TC_DA_007: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_008: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_009: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_010: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_011: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_012: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_013: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_014: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_015: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_016: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_017: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_018: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_019: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_020: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Fill allocation modal' },
    TC_DA_021: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Submit and confirm' },
    TC_DA_022: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Submit and confirm' },
    TC_DA_023: { specFile: 'web/tests/deliveryAllocation.spec.js', testTitle: 'Allocate invoices to vehicle', stepName: 'Submit and confirm' },

    // ── RETURN TO FC ──────────────────────────────────────────────────────
    TC_RFC_001: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Open Return to FC for latest vehicle' },
    TC_RFC_002: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Open Return to FC for latest vehicle' },
    TC_RFC_003: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Open Return to FC for latest vehicle' },
    TC_RFC_004: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_005: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_006: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_007: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_008: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_009: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_010: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_011: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_012: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_013: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_014: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_015: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_016: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_017: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_018: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_019: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_020: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Process all invoices through delivery + collection form' },
    TC_RFC_021: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Verify all invoices' },
    TC_RFC_022: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Verify all invoices' },
    TC_RFC_023: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Verify all invoices' },
    TC_RFC_024: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Upload RFC supporting docs (round 1)' },
    TC_RFC_025: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Upload RFC supporting docs (round 1)' },
    TC_RFC_026: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Upload RFC supporting docs (round 1)' },
    TC_RFC_027: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Upload RFC supporting docs (round 1)' },
    TC_RFC_028: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Upload RFC supporting docs (round 2)' },
    TC_RFC_029: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Click Verify RFC' },
    TC_RFC_030: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Click Verify RFC' },
    TC_RFC_031: { specFile: 'web/tests/returnToFC.spec.js', testTitle: 'Process Return-to-FC for latest vehicle', stepName: 'Click Verify RFC' },
    TC_RFC_032: { specFile: '', testTitle: '', stepName: '' }, // negative - manual
    TC_RFC_033: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Subtract collection date for all invoices (DB)' },

    // ── OBC UPLOAD ────────────────────────────────────────────────────────
    TC_OBC_001: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open upload form and select OBC type' },
    TC_OBC_002: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open upload form and select OBC type' },
    TC_OBC_003: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open upload form and select OBC type' },
    TC_OBC_004: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open upload form and select OBC type' },
    TC_OBC_005: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_OBC_006: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_OBC_007: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_OBC_008: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Select FC = CMBT, Brand = Britannia' },
    TC_OBC_009: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Upload file and submit' },
    TC_OBC_010: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Upload file and submit' },
    TC_OBC_011: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Filter status list by OBC and search' },
    TC_OBC_012: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Filter status list by OBC and search' },
    TC_OBC_013: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Filter status list by OBC and search' },
    TC_OBC_014: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open status detail and close' },
    TC_OBC_015: { specFile: 'web/tests/obcUpload.spec.js', testTitle: 'Upload OBC file for CMBT/Britannia', stepName: 'Open status detail and close' },

    // ── SEG ALLOCATION ────────────────────────────────────────────────────
    TC_SEG_001: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Open Allocation page' },
    TC_SEG_002: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia, Continue' },
    TC_SEG_003: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia, Continue' },
    TC_SEG_004: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia, Continue' },
    TC_SEG_005: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia, Continue' },
    TC_SEG_006: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select FC = CMBT, Brand = Britannia, Continue' },
    TC_SEG_007: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Pick salesman and search' },
    TC_SEG_008: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Pick salesman and search' },
    TC_SEG_009: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Pick salesman and search' },
    TC_SEG_010: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select invoice checkbox, assign and submit' },
    TC_SEG_011: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select invoice checkbox, assign and submit' },
    TC_SEG_012: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select invoice checkbox, assign and submit' },
    TC_SEG_013: { specFile: 'web/tests/seg.spec.js', testTitle: 'Allocate invoice to salesman for CMBT Britannia', stepName: 'Select invoice checkbox, assign and submit' },

    // ── COLLECTION ────────────────────────────────────────────────────────
    TC_COL_001: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Open invoice details (down arrow)' },
    TC_COL_002: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cash amount' },
    TC_COL_003: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cash amount' },
    TC_COL_004: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_005: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_006: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_007: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_008: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_009: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill cheque section' },
    TC_COL_010: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Handle UPI flow' },
    TC_COL_011: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Handle UPI flow' },
    TC_COL_012: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Handle UPI flow' },
    TC_COL_013: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Handle UPI flow' },
    TC_COL_014: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill NEFT section' },
    TC_COL_015: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Fill NEFT section' },
    TC_COL_016: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_017: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_018: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_019: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_020: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_021: { specFile: 'web/tests/collection.spec.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Submit collection (Auto split, Shop Closed) and confirm' },
    TC_COL_022: { specFile: 'mobile/tests/collection.e2e.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Click Collection card on landing' },
    TC_COL_023: { specFile: 'mobile/tests/collection.e2e.js', testTitle: 'Submit collection for current AMOUNTS', stepName: 'Click Collection card on landing' },

    // ── SEG VERIFICATION ──────────────────────────────────────────────────
    TC_SEGV_001: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Open Verification page' },
    TC_SEGV_002: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Open Deliverer tab and pick delivery row' },
    TC_SEGV_003: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Open Deliverer tab and pick delivery row' },
    TC_SEGV_004: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Pick salesman row and start verification' },
    TC_SEGV_005: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Pick salesman row and start verification' },
    TC_SEGV_006: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_007: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_008: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_009: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_010: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_011: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },
    TC_SEGV_012: { specFile: 'web/tests/segVerification.spec.js', testTitle: 'Verify or reject invoices for current verificationType', stepName: 'Run verification or rejection flow' },

    // ── CASH VERIFICATION ────────────────────────────────────────────────
    TC_CASHV_001: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Open Collection Settlement' },
    TC_CASHV_002: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Open Deliverer tab and pick delivery row' },
    TC_CASHV_003: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Open Deliverer tab and pick delivery row' },
    TC_CASHV_004: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Pick salesman settle row' },
    TC_CASHV_005: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Start verification' },
    TC_CASHV_006: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cash flow' },
    TC_CASHV_007: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cash flow' },
    TC_CASHV_008: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cash flow' },
    TC_CASHV_009: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cash flow' },
    TC_CASHV_010: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cheque flow' },
    TC_CASHV_011: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run cheque flow' },
    TC_CASHV_012: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Insert UPI bank statement (DB) and reload' },
    TC_CASHV_013: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run UPI flow' },
    TC_CASHV_014: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run UPI flow' },
    TC_CASHV_015: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Insert NEFT bank statement (DB) and reload' },
    TC_CASHV_016: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: 'Run NEFT flow' },
    TC_CASHV_017: { specFile: 'web/tests/cashVerification.spec.js', testTitle: 'Cashier verification for current SEG.verificationType', stepName: "Switch verificationType 'D' → 'S' in seg.js (in-memory + persisted)" },

    // ── CHEQUE BOUNCE ─────────────────────────────────────────────────────
    TC_CBM_001: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Open Cheque Bounce list and add new' },
    TC_CBM_002: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Open Cheque Bounce list and add new' },
    TC_CBM_003: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Open Cheque Bounce list and add new' },
    TC_CBM_004: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Fill cheque number and map FC' },
    TC_CBM_005: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Fill cheque number and map FC' },
    TC_CBM_006: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Fill cheque number and map FC' },
    TC_CBM_007: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Submit and confirm' },
    TC_CBM_008: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Admin: Add cheque bounce and map invoice', stepName: 'Submit and confirm' },
    TC_CBM_009: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Open Mark Bounce form' },
    TC_CBM_010: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Pick cheque row and select reason' },
    TC_CBM_011: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Pick cheque row and select reason' },
    TC_CBM_012: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Upload supporting docs and submit' },
    TC_CBM_013: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Upload supporting docs and submit' },
    TC_CBM_014: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Open Handover tab and trigger action' },
    TC_CBM_015: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Open Handover tab and trigger action' },
    TC_CBM_016: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Assign segregator' },
    TC_CBM_017: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Assign segregator' },
    TC_CBM_018: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Assign segregator' },
    TC_CBM_019: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Cashier: Mark bounce and handover', stepName: 'Assign segregator' },
    TC_CBM_020: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Acknowledge handover and submit' },
    TC_CBM_021: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Acknowledge handover and submit' },
    TC_CBM_022: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Acknowledge handover and submit' },
    TC_CBM_023: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Open summary and assign officer' },
    TC_CBM_024: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Open summary and assign officer' },
    TC_CBM_025: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Open summary and assign officer' },
    TC_CBM_026: { specFile: 'web/tests/chequeBounce.spec.js', testTitle: 'Seg: Acknowledge bounce and assign officer', stepName: 'Open summary and assign officer' },

    // ── CBM SEG VERIFICATION ──────────────────────────────────────────────
    TC_CBMSV_001: { specFile: 'web/tests/cbmSegVerification.spec.js', testTitle: 'CBM Seg verification', stepName: 'Open Cheque Bounce Verification list' },
    TC_CBMSV_002: { specFile: 'web/tests/cbmSegVerification.spec.js', testTitle: 'CBM Seg verification', stepName: 'Open Cheque Bounce Verification list' },
    TC_CBMSV_003: { specFile: 'web/tests/cbmSegVerification.spec.js', testTitle: 'CBM Seg verification', stepName: 'Pick ready-for-verification row' },
    TC_CBMSV_004: { specFile: 'web/tests/cbmSegVerification.spec.js', testTitle: 'CBM Seg verification', stepName: 'Run verification flow' },
    TC_CBMSV_005: { specFile: 'web/tests/cbmSegVerification.spec.js', testTitle: 'CBM Seg verification', stepName: 'Run verification flow' },

    // ── CBM CASH VERIFICATION ─────────────────────────────────────────────
    TC_CBMCV_001: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Open Cheque Bounce Recovery Verification' },
    TC_CBMCV_002: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Open Cheque Bounce Recovery Verification' },
    TC_CBMCV_003: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Open Cheque Bounce Recovery Verification' },
    TC_CBMCV_004: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Open Cheque Bounce Recovery Verification' },
    TC_CBMCV_005: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Run cash flow' },
    TC_CBMCV_006: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Run cash flow' },
    TC_CBMCV_007: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Run cash flow' },
    TC_CBMCV_008: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Run cheque flow' },
    TC_CBMCV_009: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Insert UPI bank statement (DB) and run UPI flow' },
    TC_CBMCV_010: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Insert UPI bank statement (DB) and run UPI flow' },
    TC_CBMCV_011: { specFile: 'web/tests/cbmCashVerification.spec.js', testTitle: 'CBM Cashier verification for configured payment modes', stepName: 'Insert NEFT bank statement (DB) and run NEFT flow' },

    // ── OBC ELIMINATION ───────────────────────────────────────────────────
    // Test names use the brand from CFG: "OBC Elimination [GDJGT: Godrej GT] — Happy Path"
    TC_OBCE_001: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Pre-check: obc_adjustment_date is set for fc=1 + brand=3', stepName: '' },
    TC_OBCE_002: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Pre-check: obc_adjustment_date is set for fc=1 + brand=3', stepName: '' },
    TC_OBCE_003: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Pre-check: obc_adjustment_date is set for fc=1 + brand=3', stepName: '' },
    TC_OBCE_004: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Setup: load invoice and capture DB state', stepName: '' },
    TC_OBCE_005: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Setup: load invoice and capture DB state', stepName: '' },
    TC_OBCE_006: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Setup: load invoice and capture DB state', stepName: '' },
    TC_OBCE_007: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Pre-check: no existing obc_adjustment_data entry for picked invoice', stepName: '' },
    TC_OBCE_008: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_009: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_010: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_011: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_012: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_013: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_014: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_015: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_016: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and upload Collection Report', stepName: '' },
    TC_OBCE_017: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Wait for Fully Processed and Open View', stepName: '' },
    TC_OBCE_018: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Generate per-invoice report', stepName: '' },
    TC_OBCE_019: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Generate per-invoice report', stepName: '' },
    TC_OBCE_020: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Login and re-upload same Collection Report', stepName: '' },
    TC_OBCE_021: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Verify View: Previously Captured > 0, Unique Entries = 0', stepName: '' },
    TC_OBCE_022: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Post-check: no new obc_adjustment_data entry on re-upload', stepName: '' },
    TC_OBCE_023: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Generate zero-amount file', stepName: '' },
    TC_OBCE_024: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'Verify View: all counts = 0 (all skipped)', stepName: '' },
    TC_OBCE_025: { specFile: 'web/tests/obcElimination.spec.js', testTitle: 'DB Post-check: no obc_adjustment_data for zero-amount', stepName: '' },

    // ── SEG CA ────────────────────────────────────────────────────────────
    TC_SEGCA_001: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_002: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_003: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_004: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_005: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_006: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Allocation and select FC = Begur Road, Brand = Sunpure' },
    TC_SEGCA_007: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Select invoices from soInvoices.json and click Assign' },
    TC_SEGCA_008: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Select invoices from soInvoices.json and click Assign' },
    TC_SEGCA_009: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Pick salesman and confirm assignment' },
    TC_SEGCA_010: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Pick salesman and confirm assignment' },
    TC_SEGCA_011: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Pick salesman and confirm assignment' },
    TC_SEGCA_012: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Click "Remove and Continue" if shown' },
    TC_SEGCA_013: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'If "Pending Financial Adjustment" modal shown, run Credit Adjustment upload' },
    TC_SEGCA_014: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'If "Pending Financial Adjustment" modal shown, run Credit Adjustment upload' },
    TC_SEGCA_015: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Cancel "Some invoices cannot be assigned" if shown' },
    TC_SEGCA_016: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Close modal if shown' },
    TC_SEGCA_017: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Open Handover Invoices' },
    TC_SEGCA_018: { specFile: 'web/tests/segCA.spec.js', testTitle: 'Seg Credit Adjustment for Sunpure invoices', stepName: 'Verify Sunpure invoice count matches soInvoices.json' },

    // ── SMOKE TEST ────────────────────────────────────────────────────────
    TC_SMOKE_001: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Login', stepName: '' },
    TC_SMOKE_002: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Return to FC', stepName: '' },
    TC_SMOKE_003: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'OBC Upload', stepName: '' },
    TC_SMOKE_004: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Seg', stepName: '' },
    TC_SMOKE_005: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Collection', stepName: '' },
    TC_SMOKE_006: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Seg Verification', stepName: '' },
    TC_SMOKE_007: { specFile: 'web/tests/smokeTest.spec.js', testTitle: 'Cash Verification', stepName: '' },
};
