"""Add Cheque Image Upload test cases to the existing Collection_TestCases.xlsx as a new tab."""
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

FILE = r"C:/Users/User/Downloads/Collection_TestCases.xlsx"
SHEET = "Cheque_Image_Upload"
CR = "CR-CHQ-IMG"

HEADERS = ["MODULE", "Change Request", "PLATFORM", "TEST SCENARIO", "TEST DATA",
           "TEST STEPS", "EXPECTED RESULTS", "TYPE", "SEVERITY"]

# (module, platform, scenario, data, steps, expected, type, severity)
ROWS = [
    # ============================ A. MOBILE (Salesman + Sales Officer) ============================
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify 'Scan / Add Cheque' CTA is visible on Collection > Cheque section",
     "Store: RAJ ENTERPRISE, Outstanding Rs.2989",
     "1. Login as salesman\n2. Open store\n3. Tap 'Payment Collection'\n4. Scroll to Cheque card",
     "Scan / Add Cheque button is visible, enabled, and shows 'No Cheque Payments added' placeholder beneath",
     "UI", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify camera preview with edge-frame overlay launches on Scan tap",
     "Salesman with camera permission granted",
     "1. Open Cheque card\n2. Tap 'Scan / Add Cheque'",
     "Camera opens with viewfinder, blue edge-frame overlay, 'Align all 4 edges within the frame' caption, capture (blue circle) and Cancel buttons",
     "UI", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify lighting/surface guidance banner on camera screen", "NA",
     "1. Open Scan Cheque screen",
     "Yellow banner: 'Ensure good lighting and place the cheque on a flat, dark surface for best results' displayed at top",
     "UI", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify upload analysis screen UI after capture", "Clean cheque image",
     "1. Capture cheque\n2. Observe upload screen",
     "Screen shows file name (cheque1.jpeg), 'Analysing...' header, progress text 'Reading cheque number...' and % bar updating 0 to 100",
     "UI", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Review Extracted Data bottom sheet fields",
     "Clean cheque: HDFC, Rs.2500, 02/03/2026, 456789",
     "1. Complete OCR\n2. Observe Review sheet",
     "Sheet shows: cheque thumbnail + filename, Retry button, fields Bank Name / Amount / Due Date / Cheque Number, Submit Cheque CTA",
     "UI", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify 'Cheque Added!' success screen", "Submitted cheque",
     "1. Submit cheque on Review sheet",
     "Green tick, 'Cheque Added!', 'Payment recorded successfully', summary card (Bank, Cheque No, Amount, Due Date), Done + 'Add Another Cheque' buttons",
     "UI", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify cheque chip appears on Collection landing after add",
     "1 cheque Rs.2500 added",
     "1. Submit cheque\n2. Tap Done\n3. Return to Collection landing",
     "Cheque section shows card with Bank, Cheque No, Due Date, Amount; Total updates to include cheque amount; chip count = 1",
     "UI", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify successful end-to-end cheque scan, OCR, and submit",
     "HDFC cheque, Rs.2500, 02/03/2026, No 456789",
     "1. Tap Scan\n2. Capture\n3. Wait OCR\n4. Verify extracted fields\n5. Submit",
     "All 6 metadata fields (Bank Name, Account No, IFSC, Cheque No, Date, Amount) stored in backend with OCR metadata flag; image stored; collection updated",
     "Smoke", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify OCR extracts Bank Name correctly",
     "Cheque with 'HDFC Bank Limited' printed",
     "1. Scan cheque",
     "Bank Name field auto-populated 'HDFC Bank Limited', flagged as OCR-sourced metadata",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify OCR extracts Account Number using 'A/C No' pattern",
     "Cheque with 'A/C No: 50100123456789'",
     "1. Scan cheque",
     "Account Number 50100123456789 captured in metadata",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify OCR extracts IFSC Code matching 11-char alphanumeric",
     "Cheque with 'IFSC Code: HDFC0001234'",
     "1. Scan cheque",
     "IFSC HDFC0001234 captured; format validated (4 letters + 7 alphanumeric)",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify cheque number extracted from MICR line (6-digit segment)",
     "MICR: |456789| 000123 4567890|",
     "1. Scan cheque",
     "Cheque Number = 456789 captured from first MICR segment",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify cheque Date parsed from top-right corner",
     "Cheque dated '02/03/2026' top-right",
     "1. Scan cheque",
     "Date 02/03/2026 parsed and stored; validated as current/future",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Amount extracted from amount box",
     "Numeric box Rs.2500 + words 'Two Thousand Five Hundred Only'",
     "1. Scan cheque",
     "Amount 2500 captured; cross-verified with words if confidence low",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify user can edit OCR-extracted fields before Submit",
     "Auto-filled fields",
     "1. Scan cheque\n2. On Review sheet, edit Bank Name\n3. Submit",
     "Edited value saved; backend stores both OCR-extracted and final user-edited values for audit",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Retry button re-opens camera and re-scans",
     "Existing extracted data",
     "1. On Review sheet, tap Retry",
     "Camera reopens; previous scan discarded; new image captured and re-analysed",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify 'Add Another Cheque' allows multiple cheque captures",
     "Cheque 1 added",
     "1. On success screen tap 'Add Another Cheque'\n2. Repeat scan flow",
     "Second cheque added; Landing shows 2 cheques, total updated; both stored independently",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Cheque Bounce Management screen also supports scan",
     "Bounced cheque entry pending",
     "1. Open Cheque Bounce screen\n2. Tap scan option",
     "Same scan flow opens; image + metadata captured against the bounce record",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Scan option disabled after Submit Collection",
     "Collection with cheque submitted",
     "1. Submit collection\n2. Return to store collection screen",
     "Scan / Add Cheque button is disabled / hidden; informational text shown",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Scan re-enabled when segregator rejects cheque",
     "Cheque rejected by segregator",
     "1. Segregator rejects cheque on web\n2. Salesman reopens collection",
     "Scan / Add Cheque button is re-enabled; previous cheque entry shown as rejected with reason",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Scan re-enabled when cashier rejects for data issue",
     "Cheque rejected by cashier (data issue)",
     "1. Cashier rejects with reason 'data mismatch'\n2. Salesman reopens",
     "Scan button re-enabled; user can rescan",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Scan re-enabled when cashier rejects for amount issue",
     "Cheque rejected by cashier (amount issue)",
     "1. Cashier rejects with reason 'amount issue'\n2. Salesman reopens",
     "Scan button re-enabled; user can rescan",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify Rescan BLOCKED when seg rejects after cashier-data-issue rejection",
     "Sequence: cashier reject (data) -> user rescan -> seg reject",
     "1. Cashier rejects (data)\n2. Salesman rescans\n3. Seg rejects\n4. Salesman reopens",
     "Scan button is disabled; UI shows escalation message; rescan path blocked",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify upload metadata: timestamp + user captured", "NA",
     "1. Submit cheque\n2. Inspect backend record",
     "Record contains upload timestamp (UTC), salesman/sales-officer userId, deviceId",
     "Functional", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Verify image retention policy (1 year)", "Cheque uploaded today",
     "1. Wait 1y+1d (backend)\n2. Query record",
     "Image file purged after 1 year; metadata may remain per audit policy",
     "Functional", "Medium"),
    ("Cheque Image Upload - Sales Officer", "Mobile",
     "Verify Sales Officer can scan cheque during collection verification",
     "Sales Officer role user",
     "1. Login as Sales Officer\n2. Open store\n3. Scan cheque",
     "Scan flow identical to salesman; record stored against Sales Officer userId",
     "Functional", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "OCR low confidence - 'Bank Name doesn't exist' error shown",
     "Cheque with smudged bank name",
     "1. Scan cheque",
     "Review sheet shows red error 'Bank Name [X] Doesn't Exist' under field; Submit blocked until user edits",
     "Edge", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "OCR low confidence - 'Unable to read Due date' error",
     "Cheque with unreadable date",
     "1. Scan cheque",
     "Review sheet shows error 'Unable to read Due date, Enter Manually or Scan again'; user can edit or retry",
     "Edge", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Rotated cheque image (90deg/180deg)",
     "Cheque captured upside down",
     "1. Capture rotated\n2. Wait OCR",
     "System auto-rotates and extracts, OR shows 'unable to read, please rescan' message",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Handwritten amount only (no numeric box)",
     "Cheque with words only 'Two Thousand Five Hundred Only'",
     "1. Scan cheque",
     "OCR uses words; Amount populated 2500 with low confidence flag; user prompted to confirm",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Date format variation DD-MM-YYYY vs DD/MM/YYYY vs handwritten",
     "Three cheques each format",
     "1. Scan each\n2. Review extracted date",
     "All three formats parsed; output normalised to canonical format (e.g., DD/MM/YYYY)",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Network drop during image upload", "Strong cellular drop mid-upload",
     "1. Start scan\n2. Toggle airplane mode during upload",
     "Upload fails gracefully; retry CTA shown; no partial record created",
     "Edge", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "App killed mid-OCR processing", "OCR in progress",
     "1. Start OCR\n2. Kill app\n3. Relaunch",
     "No partial record; on relaunch user must rescan; previous incomplete data discarded",
     "Edge", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Background app and resume during scan", "Active scan",
     "1. Mid scan, press Home\n2. Resume app",
     "App returns to scan screen with state preserved (or graceful restart)",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Cancel button mid-scan", "NA",
     "1. Open scan\n2. Tap Cancel",
     "Returns to Cheque collection card; no record created",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Back navigation during OCR processing", "OCR in progress",
     "1. Capture\n2. Tap device back during OCR",
     "OCR cancelled; user returns to Cheque card; no record persisted",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Very large image file (>5MB)", "High-res capture",
     "1. Scan",
     "Image compressed client-side before upload OR error 'image too large, please retry'",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Multiple cheques with same cheque number",
     "2 cheques both number 456789",
     "1. Scan cheque1\n2. Submit\n3. Scan cheque2 with same number",
     "Duplicate cheque number warning shown; user can override with confirmation OR blocked",
     "Edge", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Bank name not in master list",
     "OCR finds 'AJ Small Finance Bank' not in master list",
     "1. Scan",
     "Error 'Bank Name AJ Small Finance Bank Doesn't Exist'; user edits to valid bank or retries",
     "Edge", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Camera permission denied", "Camera permission revoked",
     "1. Tap Scan Cheque",
     "OS permission prompt; if denied, show in-app explanation + Settings deep-link; no crash",
     "Negative", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Submit Cheque without scanning (manual entry only)",
     "Empty scan",
     "1. Try to submit without scan",
     "Blocked with message 'Cheque image is mandatory'; OR if manual fallback allowed, captured with manual-entry flag (clarify with PM)",
     "Negative", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "OCR cheque number does not match user-entered cheque number",
     "OCR=456789, user edits to 999999",
     "1. Scan\n2. Edit Cheque No\n3. Submit",
     "Mismatch flagged with warning; user must confirm; final value stored with both OCR original + user override for audit",
     "Negative", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Past-dated cheque (date already passed)",
     "Cheque dated 01/01/2020",
     "1. Scan\n2. Submit",
     "Validation blocks: 'Cheque date is in the past, future dates are not allowed' (per FR-2.5)",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Invalid IFSC format (10 chars)", "IFSC: HDFC000123",
     "1. Scan\n2. Submit",
     "Format validation fails; user prompted to correct",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Blank/empty image scanned", "White page",
     "1. Scan blank",
     "OCR returns no fields; error 'No cheque detected, please rescan'",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Non-cheque image (e.g., random document)",
     "Photo of a printed letter",
     "1. Scan",
     "OCR fails to find MICR/bank patterns; error shown; rescan prompt",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Corrupted image file", "Simulate file corruption",
     "1. Capture\n2. Tamper file (test hook)\n3. Upload",
     "Server rejects with clear error; client shows retry",
     "Negative", "Medium"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Airplane mode - no scan possible", "Airplane mode ON",
     "1. Tap Scan\n2. Capture\n3. Try upload",
     "Client allows capture but upload queued/blocked; offline mode banner shown; auto-retry on reconnect (if supported) OR blocked entirely",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Scan attempted after Submit Collection",
     "Collection submitted",
     "1. Submit collection\n2. Try to tap Scan",
     "Button disabled / tap shows toast 'Cheque already submitted, contact segregator to make changes'",
     "Negative", "Critical"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Submit with missing mandatory metadata",
     "Only Cheque No filled, Bank Name blank",
     "1. Edit fields to clear Bank\n2. Submit",
     "Submit blocked with field-level errors highlighting missing values",
     "Negative", "High"),
    ("Cheque Image Upload - Salesman", "Mobile",
     "Role-based access: non-authorised user attempts scan",
     "Cashier role logged into mobile app",
     "1. Open Collection\n2. Look for scan button",
     "Either Cashier role cannot access mobile collection OR scan button is hidden",
     "Negative", "High"),

    # ============================ B. SEGREGATOR (Web) ============================
    ("Cheque Image Upload - Segregator", "Web",
     "Verify Verification dashboard renders for Salesperson tab",
     "Segregator user, date 06-Jun-2022",
     "1. Login as segregator\n2. Open Verification module",
     "List shows Salesperson rows with cols Brand/Name/Phone/Total Invoice/No Bill Backs/Bill Backs/Voucher/Total Collection/Verification/Remarks; counters Total Bill Back, Voucher, Verified, Pending populated",
     "UI", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify Salesperson / Deliverer tab switch works", "NA",
     "1. Click Deliverer tab",
     "List re-renders with deliverer-scoped rows; counters update",
     "UI", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify status pills color-coding", "Mixed rows",
     "1. Observe Verification column",
     "Ready for Verification = orange, Pending = red/yellow, Verified = green, Settled = green",
     "UI", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify search by invoice/store name works",
     "Search: 'RPL-PPL-325-908'",
     "1. Type in search box\n2. Wait for filter",
     "List filtered to matching invoices only",
     "Functional", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify 'Only Rejected Invoices' toggle filters list",
     "Mixed status invoices",
     "1. Toggle ON",
     "List filters to rows with rejected status only",
     "Functional", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify date filter picker", "Date 06-Jun-2022",
     "1. Click date\n2. Select another date",
     "List updates to selected date records",
     "Functional", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify drill-in to Salesman Details from list",
     "Salesman: Amar Narayan",
     "1. Click row",
     "Navigates to 'Invoice Verification Dashboard > Salesman Details' with header card showing Salesperson, Brand, Total Invoice, No Bill Backs, Bill Backs, Voucher, Total Collection, Cash, Cheque, UPI, Online",
     "UI", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify cheque image displays inline in Collection Mode",
     "Invoice with cheque uploaded from mobile",
     "1. Open Salesman Details\n2. Scroll to Cheque collection mode",
     "Cheque image thumbnail visible alongside Cheque Amount, Cheque Number, Due Date, Bank name; image loads without broken icon",
     "UI", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify Verify (green tick) / Reject (red cross) buttons present per invoice",
     "Pending invoice",
     "1. Open Salesman Details\n2. Scroll to invoice row",
     "Both action icons visible, enabled; remarks + icon visible",
     "UI", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify Start Verification CTA enabled",
     "Pending invoices > 0",
     "1. Open Salesman Details",
     "Start Verification button enabled when there are pending invoices",
     "UI", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify cheque - status updates to Verified",
     "Pending cheque invoice",
     "1. Click Verify (green tick)",
     "Row status -> Verified; backend updates; salesman cannot rescan",
     "Smoke", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Reject cheque - status updates and salesman scan re-enabled",
     "Pending invoice",
     "1. Click Reject\n2. Add remarks\n3. Confirm",
     "Row status -> Rejected; salesman app scan re-enabled; backend audit log entry created",
     "Functional", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Cheque image opens in full preview on click", "Image present",
     "1. Click image thumbnail",
     "Image opens in modal/lightbox with zoom; close X button works",
     "Functional", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Cross-verify cheque image vs entered cheque number",
     "Image shows 456789, entered 456789",
     "1. Visually compare\n2. Verify",
     "Match - segregator verifies",
     "Functional", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Mismatch between image cheque no and entered no",
     "Image shows 999999, entered 456789",
     "1. Visually compare\n2. Reject with reason",
     "Segregator rejects; remark 'cheque no mismatch'; salesman gets rescan",
     "Functional", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Pagination across 1279+ pages", "Large dataset",
     "1. Click page navigation / Go to Page",
     "Navigates to selected page; rows update",
     "Functional", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Empty state - no invoices to verify",
     "Salesman with 0 invoices",
     "1. Open dashboard",
     "Empty list with 'No invoices to verify' message",
     "Edge", "Low"),
    ("Cheque Image Upload - Segregator", "Web",
     "Cheque image fails to load (broken URL)",
     "Image deleted on storage",
     "1. Open Salesman Details",
     "Placeholder shown; 'Image unavailable' message; verify/reject still functional",
     "Edge", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Very high resolution cheque image rendering",
     "4K image",
     "1. Open Salesman Details",
     "Image renders with proper aspect ratio, no layout break",
     "Edge", "Low"),
    ("Cheque Image Upload - Segregator", "Web",
     "Concurrent verification by two segregators",
     "Same invoice opened twice",
     "1. Seg1 verifies\n2. Seg2 also tries to verify",
     "Second action fails with 'already verified' message; no double update",
     "Edge", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Reject -> Salesman rescans -> Re-verify",
     "Reject cycle",
     "1. Seg rejects\n2. Salesman rescans\n3. New image+data submitted\n4. Seg opens again",
     "New image visible, status back to Ready for Verification; previous reject in audit log",
     "Functional", "Critical"),
    ("Cheque Image Upload - Segregator", "Web",
     "Network drop during verify action", "NA",
     "1. Click Verify\n2. Disconnect network",
     "Action fails with retry option; no partial state update",
     "Edge", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Reject without remarks", "Empty remarks",
     "1. Click Reject\n2. Leave remarks blank\n3. Confirm",
     "Validation blocks: 'Remarks are mandatory for rejection'",
     "Negative", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify cheque with bounced status", "Bounced cheque",
     "1. Open invoice with bounced cheque",
     "UI shows bounced label; verification path may be different (clarify)",
     "Negative", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Non-segregator role tries to access Verification module",
     "Salesman/Cashier user",
     "1. Login as non-segregator\n2. Try open Verification URL",
     "Access denied OR module hidden from sidebar",
     "Negative", "High"),
    ("Cheque Image Upload - Segregator", "Web",
     "Verify same cheque twice (after refresh)",
     "Already-verified cheque",
     "1. Refresh\n2. Try verify again",
     "Verify button disabled or hidden for already-verified rows",
     "Negative", "Medium"),
    ("Cheque Image Upload - Segregator", "Web",
     "Browser zoom and responsive behavior",
     "Zoom 50% / 200%",
     "1. Set zoom\n2. View Salesman Details",
     "Layout adapts; no overlap; image scales",
     "UI", "Low"),

    # ============================ C. CASHIER (Web) ============================
    ("Cheque Image Upload - Cashier", "Web",
     "Verify 4-step wizard renders (Cash > Cheque > UPI > NEFT)",
     "Settlement entry pending",
     "1. Login as cashier\n2. Open Collection Settlement > Cash Verification",
     "Wizard shows 4 steps with current step 'Cheque verification' highlighted (orange)",
     "UI", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify Cheque step shows cheque list with pending/completed tabs",
     "Mixed cheques",
     "1. Navigate to Cheque step",
     "Tabs 'Pending' / 'Completed' visible; default to Pending; cheque list rendered with status pills",
     "UI", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify cheque image preview on right panel",
     "Cheque selected",
     "1. Click cheque entry",
     "Right panel shows cheque image preview alongside Cheque Details (Cheque No, Issue Date, Cheque Amount, Bank Name)",
     "UI", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify 'EDIT INFO' link on cheque details", "NA",
     "1. Hover on details",
     "Edit Info link visible; clickable",
     "UI", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify Reject Cheque / Verify Cheque buttons render on Pending tab",
     "Pending cheque",
     "1. Open Pending tab cheque",
     "Red 'Reject Cheque' + green 'Verify Cheque' buttons; remarks textarea above",
     "UI", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify '1 of 4 Cheques Completed' progress indicator",
     "1 verified out of 4",
     "1. Verify one cheque",
     "Progress bar updates '1 of 4 Cheques Completed' with bar fill proportion",
     "UI", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify Completed tab shows verified banner",
     "Completed cheque",
     "1. Switch to Completed tab\n2. Click cheque",
     "Green banner 'The cheque is verified' with subtitle 'All details match the invoice records. Cheque signature verified against system records.'",
     "UI", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify search by invoice / cheque no", "'562919'",
     "1. Type in search\n2. Wait filter",
     "List filtered to matching cheques",
     "Functional", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify Cheque action moves to next pending", "NA",
     "1. Click Verify Cheque",
     "Status -> verified; auto-navigate to next pending cheque OR show success state",
     "Smoke", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Reject Cheque (data issue) -> salesman scan re-enabled",
     "Cashier rejects with reason 'data mismatch'",
     "1. Add remarks\n2. Click Reject\n3. Confirm",
     "Status -> rejected; salesman app re-enables scan; audit log entry created",
     "Functional", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Reject Cheque (amount issue) -> salesman scan re-enabled",
     "Reason 'amount mismatch'",
     "1. Add remarks\n2. Reject",
     "Status -> rejected; salesman scan re-enabled",
     "Functional", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Edit Info updates cheque metadata", "Bank Name changed",
     "1. Click EDIT INFO\n2. Modify Bank Name\n3. Save",
     "Updated value persists; audit log records change with old/new values",
     "Functional", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Save & Continue moves to next step (UPI)",
     "All cheques verified",
     "1. Verify all cheques\n2. Click Save & Continue",
     "Wizard advances to UPI verification step",
     "Functional", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Prev / Next navigation across cheques", "Multiple cheques",
     "1. Click Next / Prev",
     "Active cheque highlight moves; right panel updates",
     "Functional", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify Pending -> Completed flow",
     "Pending cheque",
     "1. Verify cheque on Pending tab\n2. Switch to Completed tab",
     "Cheque appears under Completed tab with verified banner",
     "Functional", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Cheque image enlargement on click", "Image visible",
     "1. Click image",
     "Opens in modal/zoom view; can close",
     "Functional", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify rescan BLOCKED - seg rejects after cashier data-issue",
     "Sequence: cashier reject (data) -> salesman rescan -> seg reject",
     "1. Cashier rejects (data)\n2. Salesman rescans\n3. Seg rejects",
     "Salesman scan button disabled on next attempt; UI message; cashier sees final rejected state",
     "Functional", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Cheque image fails to load", "Broken URL",
     "1. Open cheque entry",
     "Placeholder + error message; verify/reject still actionable",
     "Edge", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "All cheques completed - wizard auto-advance",
     "All verified",
     "1. Verify last cheque",
     "Auto-advance to UPI step OR explicit Save & Continue prompt",
     "Edge", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Page refresh mid-verification", "Unsaved remarks typed",
     "1. Type remarks\n2. Refresh page",
     "Unsaved changes warning OR remarks discarded; verification state preserved",
     "Edge", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Browser back button", "NA",
     "1. Click browser back",
     "Either confirmation prompt OR return to Settlement landing with state preserved",
     "Edge", "Low"),
    ("Cheque Image Upload - Cashier", "Web",
     "Concurrent cashier actions on same cheque",
     "Two cashier sessions",
     "1. Cashier1 verifies\n2. Cashier2 tries reject",
     "Second action fails with stale-state error",
     "Edge", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Reject without remarks", "Empty remarks",
     "1. Click Reject without typing",
     "Blocked with 'Remarks are mandatory'",
     "Negative", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Edit Info with invalid IFSC", "IFSC: ABCD123 (7 chars)",
     "1. Edit IFSC\n2. Save",
     "Validation fails: 'IFSC must be 11 alphanumeric characters'",
     "Negative", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Skip Cheque step without verifying",
     "Some pending",
     "1. Try Save & Continue with pending cheques",
     "Blocked OR warning shown - all cheques must be actioned",
     "Negative", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Verify mismatched details (image vs data) without flagging",
     "Image shows Rs.2500, data Rs.5000",
     "1. Click Verify without correcting",
     "Either system blocks (auto-detected mismatch) OR allows but flags audit warning",
     "Negative", "Critical"),
    ("Cheque Image Upload - Cashier", "Web",
     "Non-cashier role accesses Cash Verification",
     "Salesman/Segregator user",
     "1. Try access Cash Verification URL",
     "Access denied OR sidebar item hidden",
     "Negative", "High"),
    ("Cheque Image Upload - Cashier", "Web",
     "Bank master API not responding during Edit Info",
     "Bank dropdown fails to load",
     "1. Open Edit Info",
     "Field shows error / fallback to free-text with warning",
     "Negative", "Medium"),
    ("Cheque Image Upload - Cashier", "Web",
     "Reject cheque marked as 'Settled'",
     "Settled cheque",
     "1. Try to reject completed/settled",
     "Action blocked with 'Cannot reject settled cheque'",
     "Negative", "Medium"),

    # ============================ D. BACKEND / INTEGRATION ============================
    ("Cheque Image Upload - Backend", "API",
     "Image upload endpoint accepts valid JPEG/PNG",
     "5MB JPEG",
     "1. POST image to /cheque/upload",
     "200 OK; returns image URL + metadata id",
     "Functional", "Critical"),
    ("Cheque Image Upload - Backend", "API",
     "Image upload rejects invalid MIME type", ".exe file",
     "1. POST with wrong content-type",
     "415 Unsupported Media Type",
     "Negative", "High"),
    ("Cheque Image Upload - Backend", "API",
     "Image upload size limit", "20MB image",
     "1. POST oversized file",
     "413 Payload Too Large with clear error",
     "Negative", "Medium"),
    ("Cheque Image Upload - Backend", "API",
     "OCR API timeout handling", "Slow OCR response",
     "1. Upload triggers OCR\n2. Simulate >30s response",
     "Client gets timeout error; user prompted to retry",
     "Edge", "High"),
    ("Cheque Image Upload - Backend", "API",
     "All 6 metadata fields persisted", "Successful upload",
     "1. Upload\n2. Query DB record",
     "Bank Name, Account No, IFSC, Cheque No, Date, Amount + OCR-source flags persisted",
     "Functional", "Critical"),
    ("Cheque Image Upload - Backend", "API",
     "Audit trail captures verify/reject events",
     "Verify by seg, reject by cashier",
     "1. Perform actions\n2. Query audit log",
     "Each state transition logged with userId, role, timestamp, reason",
     "Functional", "High"),
    ("Cheque Image Upload - Backend", "API",
     "Image retention 1 year purge",
     "Cheque uploaded > 1y ago",
     "1. Trigger purge job",
     "Image file removed; metadata may persist with reference flag",
     "Functional", "Medium"),
    ("Cheque Image Upload - Backend", "API",
     "OCR cheque no vs user-entered mismatch detection",
     "OCR=A, entered=B",
     "1. Submit",
     "Mismatch flag stored on record; visible to seg/cashier",
     "Functional", "High"),
    ("Cheque Image Upload - Backend", "API",
     "State machine: rescan-blocked after seg-reject-post-cashier-data-issue",
     "Sequence triggers",
     "1. Run state transitions\n2. Attempt rescan",
     "API returns 409 / state-error preventing rescan",
     "Functional", "Critical"),
    ("Cheque Image Upload - Backend", "API",
     "Concurrent verify by two segregators",
     "Same cheque id",
     "1. Two parallel verify calls",
     "One succeeds; second returns 409 / stale state",
     "Edge", "High"),
]


def main():
    wb = openpyxl.load_workbook(FILE)
    if SHEET in wb.sheetnames:
        del wb[SHEET]
    ws = wb.create_sheet(SHEET)

    # Header row
    ws.append(HEADERS)
    header_font = Font(bold=True, color="FFFFFF", size=11)
    header_fill = PatternFill("solid", fgColor="305496")
    thin = Side(border_style="thin", color="B0B0B0")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    center = Alignment(horizontal="center", vertical="center", wrap_text=True)
    left_wrap = Alignment(horizontal="left", vertical="top", wrap_text=True)

    for col_idx, _ in enumerate(HEADERS, start=1):
        cell = ws.cell(row=1, column=col_idx)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = center
        cell.border = border

    sev_fill = {
        "Critical": PatternFill("solid", fgColor="F8CBAD"),
        "High":     PatternFill("solid", fgColor="FFE699"),
        "Medium":   PatternFill("solid", fgColor="C6E0B4"),
        "Low":      PatternFill("solid", fgColor="DDEBF7"),
    }
    type_fill = {
        "Smoke":      PatternFill("solid", fgColor="FCE4D6"),
        "Functional": PatternFill("solid", fgColor="E2EFDA"),
        "UI":         PatternFill("solid", fgColor="DDEBF7"),
        "Edge":       PatternFill("solid", fgColor="FFF2CC"),
        "Negative":   PatternFill("solid", fgColor="F4CCCC"),
    }

    # Data rows
    for r, (module, platform, scenario, data, steps, expected, ttype, severity) in enumerate(ROWS, start=2):
        row_values = [module, CR, platform, scenario, data, steps, expected, ttype, severity]
        for c, v in enumerate(row_values, start=1):
            cell = ws.cell(row=r, column=c, value=v)
            cell.border = border
            cell.alignment = left_wrap
        # Conditional colour on TYPE and SEVERITY columns
        ws.cell(row=r, column=8).fill = type_fill.get(ttype, PatternFill())
        ws.cell(row=r, column=9).fill = sev_fill.get(severity, PatternFill())
        ws.cell(row=r, column=8).alignment = center
        ws.cell(row=r, column=9).alignment = center

    # Column widths tuned for readability
    widths = {1: 30, 2: 16, 3: 12, 4: 50, 5: 35, 6: 45, 7: 55, 8: 14, 9: 12}
    for col, w in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = w

    # Freeze header
    ws.freeze_panes = "A2"

    # Auto-filter
    ws.auto_filter.ref = f"A1:I{len(ROWS)+1}"

    wb.save(FILE)
    print(f"Wrote {len(ROWS)} test cases to sheet '{SHEET}' in {FILE}")
    print("Sheets now:", openpyxl.load_workbook(FILE).sheetnames)


if __name__ == "__main__":
    main()
